In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("users_recency_monetary_frequency.csv")

In [3]:
df

       Unnamed: 0  Customer_ID  Recency  Frequency  Monetary
0               0            1      344          2     16.29
1               1            2      195          2     22.77
2               2            3      364          3     10.92
3               3            4       52          5     33.29
4               4            5      179          5     78.82
...           ...          ...      ...        ...       ...
22620       22620        22621       21          2      9.69
22621       22621        22622       15          1      6.07
22622       22622        22623       10          2    128.01
22623       22623        22624       29          2     19.60
22624       22624        22625        0          9     83.62

[22625 rows x 5 columns]

In [8]:
def process(df):
    df["Recency_rank"] = df["Recency"].rank(ascending=False)
    df["Frequency_rank"] = df["Frequency"].rank(ascending=True)
    df["Monetary_rank"] = df["Monetary"].rank(ascending=True)
    df["Recency_rank"] /= df["Recency_rank"].max()
    df["Frequency_rank"] /= df["Frequency_rank"].max()
    df["Monetary_rank"] /= df["Monetary_rank"].max()
    df["RFM_Score"] = 5 * (
        15 * df["Recency_rank"] + 28 * df["Frequency_rank"] + 57 * df["Monetary_rank"]) / 100
    return df[(df["RFM_Score"] >= 4) & (df["RFM_Score"] <= 4.5)]["Customer_ID"].to_list()

In [9]:
process(df)

[14,
 44,
 109,
 112,
 165,
 174,
 181,
 188,
 210,
 217,
 245,
 266,
 274,
 282,
 308,
 334,
 339,
 386,
 395,
 398,
 408,
 432,
 504,
 528,
 533,
 536,
 551,
 563,
 597,
 632,
 634,
 651,
 658,
 669,
 678,
 698,
 740,
 741,
 756,
 853,
 907,
 911,
 932,
 940,
 943,
 977,
 983,
 1009,
 1028,
 1064,
 1098,
 1134,
 1165,
 1170,
 1241,
 1242,
 1257,
 1270,
 1314,
 1320,
 1340,
 1347,
 1395,
 1420,
 1471,
 1494,
 1495,
 1525,
 1528,
 1540,
 1572,
 1610,
 1613,
 1626,
 1642,
 1649,
 1658,
 1684,
 1690,
 1701,
 1716,
 1727,
 1733,
 1750,
 1763,
 1783,
 1820,
 1821,
 1823,
 1853,
 1859,
 1882,
 1893,
 1894,
 1916,
 1940,
 1972,
 1985,
 2016,
 2050,
 2058,
 2063,
 2077,
 2089,
 2095,
 2100,
 2108,
 2127,
 2133,
 2177,
 2243,
 2245,
 2261,
 2288,
 2302,
 2310,
 2312,
 2315,
 2402,
 2404,
 2409,
 2423,
 2428,
 2432,
 2443,
 2453,
 2478,
 2490,
 2524,
 2525,
 2533,
 2548,
 2552,
 2671,
 2717,
 2746,
 2750,
 2752,
 2762,
 2795,
 2800,
 2811,
 2832,
 2842,
 2843,
 2926,
 2935,
 2965,
 2967,
 2990,
 3050,
 3091,
 3103,
 3114,
 3139,
 3180,
 3182,
 3183,
 3216,
 3244,
 3255,
 3263,
 3290,
 3316,
 3344,
 3346,
 3347,
 3352,
 3359,
 3365,
 3366,
 3371,
 3373,
 3378,
 3389,
 3414,
 3417,
 3420,
 3421,
 3433,
 3439,
 3449,
 3456,
 3458,
 3463,
 3470,
 3476,
 3480,
 3481,
 3484,
 3487,
 3489,
 3492,
 3499,
 3500,
 3503,
 3511,
 3524,
 3530,
 3538,
 3539,
 3550,
 3551,
 3588,
 3599,
 3607,
 3621,
 3644,
 3648,
 3652,
 3657,
 3662,
 3673,
 3674,
 3675,
 3676,
 3681,
 3686,
 3687,
 3697,
 3707,
 3711,
 3715,
 3719,
 3723,
 3725,
 3731,
 3732,
 3734,
 3743,
 3744,
 3749,
 3751,
 3754,
 3758,
 3759,
 3761,
 3767,
 3770,
 3771,
 3773,
 3774,
 3778,
 3782,
 3783,
 3785,
 3787,
 3788,
 3796,
 3803,
 3823,
 3829,
 3840,
 3841,
 3854,
 3855,
 3856,
 3900,
 3928,
 3934,
 3941,
 3945,
 3949,
 3978,
 4024,
 4026,
 4042,
 4059,
 4072,
 4084,
 4113,
 4146,
 4223,
 4246,
 4316,
 4342,
 4404,
 4427,
 4450,
 4455,
 4480,
 4497,
 4506,
 4542,
 4545,
 4577,
 4587,
 4604,
 4623,
 4629,
 4672,
 4701,
 4733,
 4789,
 4802,
 4887,
 4889,
 4897,
 4909,
 4961,
 4995,
 5034,
 5038,
 5057,
 5059,
 5071,
 5083,
 5090,
 5104,
 5124,
 5127,
 5159,
 5180,
 5214,
 5243,
 5257,
 5262,
 5273,
 5280,
 5288,
 5298,
 5312,
 5317,
 5344,
 5357,
 5367,
 5371,
 5378,
 5388,
 5441,
 5448,
 5457,
 5475,
 5482,
 5486,
 5496,
 5532,
 5535,
 5537,
 5541,
 5569,
 5584,
 5601,
 5647,
 5733,
 5735,
 5753,
 5770,
 5776,
 5778,
 5825,
 5846,
 5849,
 5864,
 5866,
 5888,
 5889,
 5899,
 5905,
 5919,
 5921,
 5923,
 5924,
 5939,
 5942,
 5954,
 5970,
 5971,
 6013,
 6044,
 6045,
 6053,
 6070,
 6075,
 6090,
 6117,
 6155,
 6173,
 6175,
 6179,
 6183,
 6185,
 6192,
 6193,
 6195,
 6196,
 6228,
 6247,
 6262,
 6273,
 6316,
 6317,
 6332,
 6359,
 6360,
 6377,
 6409,
 6438,
 6441,
 6442,
 6448,
 6462,
 6486,
 6509,
 6513,
 6528,
 6571,
 6572,
 6582,
 6583,
 6663,
 6667,
 6710,
 6722,
 6729,
 6764,
 6770,
 6773,
 6788,
 6799,
 6803,
 6804,
 6812,
 6818,
 6819,
 6832,
 6834,
 6843,
 6854,
 6857,
 6863,
 6881,
 7022,
 7142,
 7166,
 7232,
 7235,
 7244,
 7258,
 7295,
 7297,
 7300,
 7302,
 7307,
 7308,
 7314,
 7322,
 7323,
 7330,
 7336,
 7338,
 7341,
 7342,
 7343,
 7344,
 7366,
 7375,
 7389,
 7440,
 7443,
 7451,
 7456,
 7460,
 7461,
 7463,
 7469,
 7516,
 7534,
 7542,
 7551,
 7555,
 7557,
 7560,
 7592,
 7707,
 7763,
 7794,
 7837,
 7887,
 7934,
 7952,
 7957,
 7999,
 8015,
 8020,
 8024,
 8032,
 8035,
 8066,
 8079,
 8096,
 8097,
 8101,
 8103,
 8106,
 8107,
 8121,
 8122,
 8123,
 8133,
 8137,
 8141,
 8147,
 8152,
 8154,
 8158,
 8159,
 8163,
 8164,
 8173,
 8180,
 8186,
 8228,
 8257,
 8267,
 8282,
 8314,
 8319,
 8320,
 8321,
 8328,
 8332,
 8339,
 8340,
 8345,
 8351,
 8363,
 8367,
 8375,
 8377,
 8413,
 8418,
 8421,
 8453,
 8454,
 8457,
 8480,
 8491,
 8504,
 8513,
 8514,
 8565,
 8566,
 8574,
 8576,
 8666,
 8673,
 8678,
 8719,
 8724,
 8740,
 8742,
 8743,
 8756,
 8759,
 8760,
 8762,
 8763,
 8768,
 8771,
 8772,
 8781,
 8791,
 8820,
 8832,
 8842,
 8848,
 8858,
 8862,
 8869,
 8872,
 8910,
 8929,
 8939,
 8944,
 8970,
 9004,
 9013,
 9049,
 9086,
 9088,
 9091,
 9093,
 9094,
 9095,
 9125,
 9221,
 9231,
 9270,
 9311,
 9329,
 9346,
 9419,
 9437,
 9447,
 9457,
 9506,
 9523,
 9524,
 9605,
 9686,
 9745,
 9749,
 9752,
 9755,
 9760,
 9761,
 9766,
 9833,
 9850,
 9859,
 9860,
 9862,
 9863,
 9880,
 9883,
 9884,
 9902,
 9931,
 9945,
 9948,
 9952,
 9955,
 9956,
 9960,
 9961,
 9970,
 9974,
 9975,
 9981,
 9987,
 9989,
 9992,
 9995,
 10002,
 10015,
 10017,
 10036,
 10045,
 10065,
 10067,
 10074,
 10087,
 10088,
 10089,
 10092,
 10093,
 10097,
 10104,
 10107,
 10117,
 10119,
 10125,
 10126,
 10137,
 10142,
 10149,
 10151,
 10160,
 10166,
 10171,
 10174,
 10178,
 10181,
 10188,
 10195,
 10196,
 10198,
 10211,
 10212,
 10213,
 10223,
 10226,
 10233,
 10236,
 10237,
 10246,
 10253,
 10255,
 10266,
 10267,
 10279,
 10287,
 10292,
 10303,
 10306,
 10307,
 10309,
 10327,
 10339,
 10352,
 10353,
 10359,
 10369,
 10406,
 10424,
 10437,
 10438,
 10439,
 10443,
 10445,
 10452,
 10454,
 10458,
 10463,
 10465,
 10488,
 10489,
 10501,
 10511,
 10521,
 10533,
 10540,
 10544,
 10548,
 10556,
 10567,
 10573,
 10583,
 10584,
 10596,
 10600,
 10604,
 10611,
 10613,
 10616,
 10628,
 10651,
 10652,
 10655,
 10658,
 10661,
 10673,
 10676,
 10684,
 10687,
 10691,
 10694,
 10697,
 10701,
 10712,
 10714,
 10745,
 10749,
 10750,
 10751,
 10762,
 10763,
 10771,
 10781,
 10787,
 10789,
 10800,
 10807,
 10808,
 10817,
 10821,
 10842,
 10856,
 10860,
 10861,
 10865,
 10879,
 10883,
 10889,
 10905,
 10908,
 10913,
 10952,
 10953,
 10962,
 10966,
 10970,
 10977,
 10987,
 10989,
 10991,
 10994,
 11023,
 11035,
 11036,
 11043,
 11044,
 11056,
 11058,
 11059,
 11069,
 11073,
 11075,
 11081,
 11086,
 11090,
 11094,
 11097,
 11129,
 11153,
 11156,
 11157,
 11158,
 11161,
 11166,
 11170,
 11172,
 11173,
 11180,
 11181,
 11182,
 11183,
 11208,
 11219,
 11224,
 11232,
 11233,
 11281,
 11309,
 11314,
 11319,
 11325,
 11332,
 11335,
 11346,
 11390,
 11431,
 11434,
 11437,
 11460,
 11463,
 11464,
 11468,
 11469,
 11490,
 11491,
 11499,
 11519,
 11521,
 11536,
 11554,
 11563,
 11573,
 11607,
 11610,
 11614,
 11621,
 11625,
 11646,
 11651,
 11656,
 11658,
 11659,
 11688,
 11691,
 11698,
 11709,
 11716,
 11730,
 11745,
 11808,
 11809,
 11812,
 11817,
 11830,
 11835,
 11857,
 11865,
 11876,
 11886,
 11889,
 11904,
 11906,
 11907,
 11908,
 11913,
 11914,
 11917,
 11924,
 11930,
 11939,
 11942,
 11947,
 11949,
 11952,
 11960,
 11971,
 11972,
 11979,
 11981,
 11984,
 11998,
 12003,
 12004,
 12005,
 12008,
 12013,
 12018,
 12021,
 12025,
 12029,
 12031,
 12034,
 12035,
 12042,
 12043,
 12051,
 12053,
 12054,
 12060,
 12070,
 12071,
 12074,
 12076,
 12080,
 12084,
 12085,
 12086,
 12088,
 12094,
 12101,
 12102,
 12107,
 12112,
 12113,
 12114,
 12126,
 12143,
 12147,
 12156,
 12165,
 12170,
 12174,
 12181,
 12187,
 12204,
 12209,
 12216,
 12217,
 12218,
 12219,
 12220,
 12226,
 12243,
 12248,
 12251,
 12253,
 12255,
 12260,
 12271,
 12277,
 12290,
 12291,
 12294,
 12307,
 12336,
 12353,
 12360,
 12365,
 12366,
 12369,
 12370,
 12372,
 12376,
 12380,
 12382,
 12385,
 12386,
 12389,
 12401,
 12402,
 12407,
 12417,
 12431,
 12433,
 12442,
 12443,
 12450,
 12479,
 12481,
 12483,
 12487,
 12488,
 12490,
 12497,
 12498,
 12500,
 12518,
 12521,
 12533,
 12546,
 12563,
 12593,
 12631,
 12645,
 12647,
 12653,
 12674,
 12677,
 12683,
 12692,
 12700,
 12718,
 12722,
 ...]

In [7]:
df

,Unnamed: 0,Customer_ID,Recency,Frequency,Monetary,Recency_rank,Frequency_rank,Monetary_rank
0,0,1,344,2,16.29,0.041617,0.374939,0.389834
1,1,2,195,2,22.77,0.426423,0.374939,0.488751
2,2,3,364,3,10.92,0.000997,0.528619,0.268464
3,3,4,52,5,33.29,0.735238,0.694873,0.594807
4,4,5,179,5,78.82,0.453068,0.694873,0.794166
...,...,...,...,...,...,...,...,...
22620,22620,22621,21,2,9.69,0.864740,0.374939,0.237834
22621,22621,22622,15,1,6.07,0.902702,0.139271,0.122254
22622,22622,22623,10,2,128.01,0.939114,0.374939,0.871249
22623,22623,22624,29,2,19.60,0.823256,0.374939,0.442365
22624,22624,22625,0,9,83.62,1.000000,0.838983,0.805392