In [31]:
import pandas as pd

In [36]:
def process(df):
    df["Date"] = pd.to_datetime(df["Date"], format="%d/%m/%Y")
    f1 = df.groupby("Customer_ID").agg(
        Monetary=("Sales_Amount", "sum"), Recency=("Date", "max"), 
        Frequency=("Transaction_ID", "count")).reset_index()
    f1["Recency"] = (df["Date"].max() - f1["Recency"]).dt.days
    return f1[["Customer_ID", "Recency", "Frequency", "Monetary"]]

In [37]:
df = pd.read_csv("customer_transactions_log.csv")

In [38]:
df

,Unnamed: 0,Date,Customer_ID,Transaction_ID,SKU_Category,SKU,Quantity,Sales_Amount
0,1,02/01/2016,2547,1,X52,0EM7L,1.0,3.13
1,2,02/01/2016,822,2,2ML,68BRQ,1.0,5.46
2,3,02/01/2016,3686,3,0H2,CZUZX,1.0,6.35
3,4,02/01/2016,3719,4,0H2,549KK,1.0,5.59
4,5,02/01/2016,9200,5,0H2,K8EHH,1.0,6.88
...,...,...,...,...,...,...,...,...
131701,131702,04/07/2016,20203,32900,IEV,FO112,3.0,6.46
131702,131703,04/07/2016,20203,32900,N8U,I36F2,1.0,4.50
131703,131704,04/07/2016,20203,32900,U5F,4X8P4,1.0,5.19
131704,131705,04/07/2016,20203,32900,0H2,ZVTO4,1.0,4.57
131705,131706,04/07/2016,20203,32900,Q4N,QM9BP,1.0,13.68

In [41]:
process(df).to_csv("users_recency_monetary_frequency.csv")